In [ ]:
from keras.datasets import imdb

Using TensorFlow backend.


In [ ]:
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

17465344/17464789 [==============================] - 1s 0us/step


In [ ]:
train_data

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [ ]:
train_data.shape

(25000,)

In [ ]:
test_data

array([list([1, 591, 202, 14, 31, 6, 717, 10, 10, 2, 2, 5, 4, 360, 7, 4, 177, 5760, 394, 354, 4, 123, 9, 1035, 1035, 1035, 10, 10, 13, 92, 124, 89, 488, 7944, 100, 28, 1668, 14, 31, 23, 27, 7479, 29, 220, 468, 8, 124, 14, 286, 170, 8, 157, 46, 5, 27, 239, 16, 179, 2, 38, 32, 25, 7944, 451, 202, 14, 6, 717]),
       list([1, 14, 22, 3443, 6, 176, 7, 5063, 88, 12, 2679, 23, 1310, 5, 109, 943, 4, 114, 9, 55, 606, 5, 111, 7, 4, 139, 193, 273, 23, 4, 172, 270, 11, 7216, 2, 4, 8463, 2801, 109, 1603, 21, 4, 22, 3861, 8, 6, 1193, 1330, 10, 10, 4, 105, 987, 35, 841, 2, 19, 861, 1074, 5, 1987, 2, 45, 55, 221, 15, 670, 5304, 526, 14, 1069, 4, 405, 5, 2438, 7, 27, 85, 108, 131, 4, 5045, 5304, 3884, 405, 9, 3523, 133, 5, 50, 13, 104, 51, 66, 166, 14, 22, 157, 9, 4, 530, 239, 34, 8463, 2801, 45, 407, 31, 7, 41, 3778, 105, 21, 59, 299, 12, 38, 950, 5, 4521, 15, 45, 629, 488, 2733, 127, 6, 52, 292, 17, 4, 6936, 185, 132, 1988, 5304, 1799, 488, 2693, 47, 6, 392, 173, 4, 2, 4378, 270, 2352, 4, 1500, 7, 

In [ ]:
test_data.shape

(25000,)

In [ ]:
train_labels

array([1, 0, 0, ..., 0, 1, 0])

In [ ]:
train_labels.shape

(25000,)

In [ ]:
test_labels

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
test_labels.shape

(25000,)

In [ ]:
# We will need to vectorize the data because you can not feed lists of integers into a neural network. 
# You have to turn your lists into tensors. 

In [ ]:
import numpy as np

In [ ]:
def vectorize_sequences(sequences, dimension=10000):
  results = np.zeros((len(sequences), dimension))
  for i, sequence in enumerate(sequences):
    results[i, sequence] = 1
  return results

In [ ]:
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

In [ ]:
x_train[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [ ]:
x_train.shape

(25000, 10000)

In [ ]:
x_test

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [ ]:
x_test.shape

(25000, 10000)

In [ ]:
#Vectorize your y labels
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [ ]:
from keras import models
from keras import layers

In [ ]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

Configuring the optimizer

In [ ]:
from keras import optimizers

In [ ]:
model.compile(optimizer=optimizers.RMSprop(lr=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

Setting aside a validation test

In [ ]:
x_val = x_train[:10000]
partial_x_train = x_train[10000:]

In [ ]:
y_val = y_train[:10000]
partial_y_train = y_train[10000:]

Training the model

In [ ]:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])

In [ ]:
history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs=20,
                    batch_size=512,
                    validation_data=(x_val, y_val))

Train on 15000 samples, validate on 10000 samples
Epoch 1/20
15000/15000 [==============================] - 1s 74us/step - loss: 0.0075 - acc: 0.9978 - val_loss: 0.7011 - val_acc: 0.8665
Epoch 2/20
15000/15000 [==============================] - 1s 69us/step - loss: 0.0016 - acc: 0.9999 - val_loss: 0.7449 - val_acc: 0.8649
Epoch 3/20
15000/15000 [==============================] - 1s 70us/step - loss: 0.0039 - acc: 0.9989 - val_loss: 0.7603 - val_acc: 0.8653
Epoch 4/20
15000/15000 [==============================] - 1s 68us/step - loss: 9.1991e-04 - acc: 0.9999 - val_loss: 0.7942 - val_acc: 0.8650
Epoch 5/20
15000/15000 [==============================] - 1s 68us/step - loss: 8.1297e-04 - acc: 0.9999 - val_loss: 0.9370 - val_acc: 0.8488
Epoch 6/20
15000/15000 [==============================] - 1s 70us/step - loss: 0.0018 - acc: 0.9995 - val_loss: 0.8520 - val_acc: 0.8639
Epoch 7/20
15000/15000 [==============================] - 1s 70us/step - loss: 4.0802e-04 - acc: 1.0000 - val_loss: 0.88

In [ ]:
history_dict =  history.history
history_dict.keys()

dict_keys(['val_loss', 'val_acc', 'loss', 'acc'])

Plotting the training and validation loss

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
history_dict = history.history
loss_values = history_dict['loss']
val_loss = history_dict['val_loss']

epochs = range(1, len(history_dict['acc']) + 1)

plt.plot(epochs, loss_values, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')

plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

In [ ]:
plt.clf()
acc_values = history_dict['acc']
val_acc_values = history_dict['val_acc']

plt.plot(epochs, acc_values, 'bo', label='Training acc')
plt.plot(epochs, val_acc_values, 'b', label='Validation acc')

plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Loss')

plt.legend()

plt.show()

Retraining our model from scratch

In [ ]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [ ]:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=4, batch_size=512)

Epoch 1/4
25000/25000 [==============================] - 1s 46us/step - loss: 0.4591 - accuracy: 0.8236
Epoch 2/4
25000/25000 [==============================] - 1s 43us/step - loss: 0.2632 - accuracy: 0.9080
Epoch 3/4
25000/25000 [==============================] - 1s 45us/step - loss: 0.2011 - accuracy: 0.9281
Epoch 4/4
25000/25000 [==============================] - 1s 45us/step - loss: 0.1676 - accuracy: 0.9414


In [ ]:
results = model.evaluate(x_test, y_test)

25000/25000 [==============================] - 2s 72us/step


In [ ]:
results

[0.2935345567846298, 0.8849599957466125]

In [ ]:
model.predict(x_test)

array([[0.19349007],
       [0.9999434 ],
       [0.91129994],
       ...,
       [0.10449556],
       [0.07771299],
       [0.6628069 ]], dtype=float32)

In [ ]:
x_test.shape

(25000, 10000)

In [ ]:
x_test_predict = model.predict(x_test)

In [ ]:
x_test_predict.shape

(25000, 1)